spring.application.name=shop-inventory-app

# Supabase Connection Parameters (Changed port 5432 -> 6543 for Transaction Pooler)
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.okanezqedfcarinbqnlg
spring.datasource.password=091255456Bryne
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool Settings (Prevents EMAXCONNSESSION errors)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LegacySupply API Integration Parameters (Lab 3)
LS_CLIENT_ID=23-1498-418
LS_API_KEY=LSK-D7CCC0B6BF5993F1C549
